import { Worksheet, ExportFormat } from '../types';

// Helper function to get field value by partial question match
function getFieldValue(worksheet: Worksheet, partialQuestion: string): string {
	const field = worksheet.fields.find(f =>
		f.question.toLowerCase().includes(partialQuestion.toLowerCase())
	);
	return field ? (worksheet.responses[field.id] || '') : '';
}

// Helper to generate a slug ID from title
function slugify(text: string): string {
	if (!text) return 'unnamed';
	return text
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '_')
		.replace(/_+/g, '_')
		.replace(/^_|_$/g, '');
}

export function generateMarkdown(worksheet: Worksheet): string {
	const typeLabels: Record<string, string> = {
		skill: 'Skill',
		agent: 'Agent',
		workflow: 'Workflow',
		mcp: 'MCP',
	};

	let markdown = `# ${worksheet.title}\n\n`;
	markdown += `**Type:** ${typeLabels[worksheet.type] || worksheet.type}\n\n`;
	markdown += `**Created:** ${new Date(worksheet.createdAt).toLocaleDateString()}\n\n`;
	markdown += `**Status:** ${worksheet.isComplete ? '✅ Complete' : '📝 In Progress'}\n\n`;
	markdown += `---\n\n`;

	worksheet.fields.forEach((field, index) => {
		const response = worksheet.responses[field.id] || '';
		markdown += `## ${index + 1}. ${field.question}\n\n`;

		if (field.required) {
			markdown += `> **Required**\n\n`;
		}

		if (response) {
			markdown += `${response}\n\n`;
		} else {
			markdown += `_\n\n`;
		}

		if (field.explanation) {
			markdown += `> **Understanding:** ${field.explanation}\n\n`;
		}

		markdown += `---\n\n`;
	});

	markdown += `---\n\n`;
	markdown += `*Generated by AI Worksheet Generator*\n`;

	return markdown;
}

export function generateHTML(worksheet: Worksheet): string {
	const typeLabels: Record<string, string> = {
		skill: 'Skill',
		agent: 'Agent',
		workflow: 'Workflow',
		mcp: 'MCP',
	};

	return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>${worksheet.title}</title>
	<style>
		* { box-sizing: border-box; margin: 0; padding: 0; }
		body {
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
			line-height: 1.6;
			max-width: 800px;
			margin: 0 auto;
			padding: 2rem;
			color: #1f2937;
			background: #f9fafb;
		}
		.header {
			text-align: center;
			margin-bottom: 2rem;
			padding-bottom: 1rem;
			border-bottom: 2px solid #e5e7eb;
		}
		.header h1 { font-size: 1.75rem; color: #111827; margin-bottom: 0.5rem; }
		.header .meta { color: #6b7280; font-size: 0.875rem; }
		.field {
			background: white;
			border-radius: 0.75rem;
			padding: 1.5rem;
			margin-bottom: 1.5rem;
			border: 1px solid #e5e7eb;
			box-shadow: 0 1px 3px rgba(0,0,0,0.1);
		}
		.field-header {
			display: flex;
			align-items: flex-start;
			gap: 1rem;
			margin-bottom: 1rem;
		}
		.field-number {
			width: 2rem;
			height: 2rem;
			border-radius: 50%;
			background: #6366f1;
			color: white;
			display: flex;
			align-items: center;
			justify-content: center;
			font-weight: bold;
			flex-shrink: 0;
		}
		.field-question {
			font-size: 1.125rem;
			font-weight: 600;
			color: #111827;
		}
		.required { color: #ef4444; }
		.response-box {
			background: #f3f4f6;
			border-radius: 0.5rem;
			padding: 1rem;
			min-height: 4rem;
			font-family: monospace;
			white-space: pre-wrap;
			border: 1px dashed #d1d5db;
		}
		.response-box.empty { color: #9ca3af; font-style: italic; }
		.explanation {
			margin-top: 1rem;
			padding: 1rem;
			background: #eef2ff;
			border-radius: 0.5rem;
			font-size: 0.875rem;
			color: #4338ca;
		}
		.footer {
			text-align: center;
			margin-top: 2rem;
			padding-top: 1rem;
			border-top: 1px solid #e5e7eb;
			color: #6b7280;
			font-size: 0.875rem;
		}
		@media print {
			body { background: white; }
			.field { box-shadow: none; border: 1px solid #d1d5db; }
		}
	</style>
</head>
<body>
	<div class="header">
		<h1>${worksheet.title}</h1>
		<div class="meta">
			<span>Type: ${typeLabels[worksheet.type]}</span> |
			<span>Status: ${worksheet.isComplete ? 'Complete' : 'In Progress'}</span> |
			<span>Created: ${new Date(worksheet.createdAt).toLocaleDateString()}</span>
		</div>
	</div>

	${worksheet.fields
		.map((field, index) => {
			const response = worksheet.responses[field.id] || '';
			return `
		<div class="field">
			<div class="field-header">
				<div class="field-number">${index + 1}</div>
				<div class="field-question">
					${field.question}${field.required ? ' <span class="required">*</span>' : ''}
				</div>
			</div>
			<div class="response-box ${!response ? 'empty' : ''}">${
				response || 'Your response goes here...'
			}</div>
			${
				field.explanation
					? `<div class="explanation"><strong>Understanding:</strong> ${field.explanation}</div>`
					: ''
			}
		</div>
	`;
		})
		.join('')}

	<div class="footer">
		<p>Generated by AI Worksheet Generator</p>
	</div>
</body>
</html>`;
}

export function generateJSON(worksheet: Worksheet): string {
	return JSON.stringify(
		{
			...worksheet,
			fields: worksheet.fields.map(({ id, question, type }) => ({
				id,
				question,
				type,
				response: worksheet.responses[id] || '',
			})),
		},
		null,
		2
	);
}

export async function generatePDF(worksheet: Worksheet): Promise<Blob> {
	// Dynamically import jspdf
	const { jsPDF } = await import('jspdf');

	const doc = new jsPDF();
	const pageWidth = doc.internal.pageSize.getWidth();
	const margin = 20;
	const contentWidth = pageWidth - margin * 2;
	let y = 20;

	// Title
	doc.setFontSize(20);
	doc.setTextColor(99, 102, 241);
	doc.text(worksheet.title, margin, y);
	y += 10;

	// Meta info
	doc.setFontSize(10);
	doc.setTextColor(107, 114, 128);
	const typeLabels: Record<string, string> = {
		skill: 'Skill',
		agent: 'Agent',
		workflow: 'Workflow',
		mcp: 'MCP',
	};
	doc.text(
		`Type: ${typeLabels[worksheet.type]} | Status: ${worksheet.isComplete ? 'Complete' : 'In Progress'} | Created: ${new Date(worksheet.createdAt).toLocaleDateString()}`,
		margin,
		y
	);
	y += 15;

	// Divider
	doc.setDrawColor(229, 231, 235);
	doc.line(margin, y, pageWidth - margin, y);
	y += 10;

	// Fields
	worksheet.fields.forEach((field, index) => {
		const response = worksheet.responses[field.id] || '';

		// Check if we need a new page
		if (y > 270) {
			doc.addPage();
			y = 20;
		}

		// Question number
		doc.setFillColor(99, 102, 241);
		doc.circle(margin + 5, y - 2, 5, 'F');
		doc.setTextColor(255, 255, 255);
		doc.setFontSize(10);
		doc.text(String(index + 1), margin + 3.5, y);

		// Question
		doc.setTextColor(31, 41, 55);
		doc.setFontSize(12);
		const questionLines = doc.splitTextToSize(field.question, contentWidth - 20);
		doc.text(questionLines, margin + 15, y);
		y += questionLines.length * 6 + 5;

		// Response
		doc.setFillColor(249, 250, 251);
		doc.roundedRect(margin + 15, y, contentWidth - 15, response ? 20 : 15, 2, 2, 'F');
		doc.setFontSize(10);
		doc.setTextColor(107, 114, 128);
		if (response) {
			doc.setTextColor(31, 41, 55);
			const responseLines = doc.splitTextToSize(response, contentWidth - 25);
			doc.text(responseLines.slice(0, 3), margin + 18, y + 5);
		} else {
			doc.text('Your response...', margin + 18, y + 5);
		}
		y += response ? 30 : 25;

		// Explanation (if any)
		if (field.explanation) {
			doc.setFillColor(238, 242, 255);
			doc.roundedRect(margin + 15, y, contentWidth - 15, 12, 2, 2, 'F');
			doc.setFontSize(9);
			doc.setTextColor(99, 102, 241);
			const expLines = doc.splitTextToSize(`💡 ${field.explanation}`, contentWidth - 25);
			doc.text(expLines.slice(0, 2), margin + 18, y + 5);
			y += expLines.length * 4 + 10;
		}

		y += 5;
	});

	// Footer
	doc.setFontSize(8);
	doc.setTextColor(156, 163, 175);
	doc.text('Generated by AI Worksheet Generator', pageWidth / 2, 290, { align: 'center' });

	return doc.output('blob');
}

// ============================================================
// PRODUCTION-READY REGISTRY GENERATORS
// ============================================================

export function generateAssetDocument(worksheet: Worksheet): string {
	switch (worksheet.type) {
		case 'skill':
			return generateSkillRegistry(worksheet);
		case 'agent':
			return generateAgentIdentity(worksheet);
		case 'workflow':
			return generateWorkflowRegistry(worksheet);
		case 'mcp':
			return generateMCPServerRegistry(worksheet);
		default:
			return generateSkillRegistry(worksheet);
	}
}

function generateSkillRegistry(worksheet: Worksheet): string {
	const skillId = slugify(worksheet.title);
	const name = getFieldValue(worksheet, 'name');
	const category = getFieldValue(worksheet, 'category');
	const primaryFunction = getFieldValue(worksheet, 'primary function') || getFieldValue(worksheet, 'function');
	const inputs = getFieldValue(worksheet, 'inputs');
	const outputs = getFieldValue(worksheet, 'outputs');
	const bestPractices = getFieldValue(worksheet, 'best practices');
	const useCases = getFieldValue(worksheet, 'use cases');
	const role = getFieldValue(worksheet, 'role');
	const mandates = getFieldValue(worksheet, 'mandates');
	const tools = getFieldValue(worksheet, 'tools');

	// Check if this is a comprehensive skill spec
	const hasSystemPrompt = getFieldValue(worksheet, 'system prompt') || getFieldValue(worksheet, 'operational rules');

	if (hasSystemPrompt || role) {
		// Comprehensive skill with system prompt
		return `SKILL_REGISTRY:
  ID: "${skillId}"
  Version: "1.0.0"
  Classification: "${category || 'General Purpose'}"
  Runtime_Environment: "Python 3.11 / Node.js 20 compatible"
  Target_Execution_Tiers: "Multi-Agent Networks, Sequential Workflows, Direct API Call"

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "${name.replace(/[^a-zA-Z0-9]/g, '')}Inputs",
  "type": "object",
  "properties": {
    "core_topic": {
      "type": "string",
      "description": "Primary subject matter or task definition."
    },
    "format_constraints": {
      "type": "object",
      "properties": {
        "video_length_seconds": { "type": "integer", "minimum": 15, "maximum": 900 },
        "aspect_ratio": { "type": "string", "enum": ["16:9", "9:16", "1:1"] }
      },
      "required": ["video_length_seconds"]
    },
    "audience_persona": {
      "type": "string",
      "description": "Target demographic dictating tone parameters."
    },
    "source_material": {
      "type": "string",
      "description": "Optional: Raw text research notes or base drafts."
    }
  },
  "required": ["core_topic", "audience_persona"]
}

{
  "title": "${name.replace(/[^a-zA-Z0-9]/g, '')}Outputs",
  "type": "object",
  "properties": {
    "media_package": {
      "type": "object",
      "properties": {
        "primary_asset_url": { "type": "string", "format": "uri" },
        "audio_narration_url": { "type": "string", "format": "uri" }
      }
    },
    "text_assets": {
      "type": "object",
      "properties": {
        "timestamped_script_markdown": { "type": "string" },
        "subtitle_file_vtt": { "type": "string" },
        "seo_metadata_packet": {
          "type": "object",
          "properties": {
            "optimized_titles": { "type": "array", "items": { "type": "string" } },
            "description_raw": { "type": "string" },
            "tags": { "type": "array", "items": { "type": "string" } }
          }
        }
      }
    }
  }
}

SYSTEM_PROMPT_PAYLOAD:
${role || primaryFunction || 'You are operating as a specialized AI skill designed to execute discrete tasks with precision and consistency.'}

OPERATIONAL CODE RULES:
${mandates || bestPractices || '1. Execute with high accuracy and attention to detail.\n2. Maintain consistent output format.\n3. Handle edge cases gracefully.'}

${inputs ? `INPUT REQUIREMENTS:\n${inputs}` : ''}

${outputs ? `OUTPUT SPECIFICATIONS:\n${outputs}` : ''}

${useCases ? `COMMON USE CASES:\n${useCases}` : ''}
`;
	}

	// Standard skill format
	return `SKILL_REGISTRY:
  ID: "${skillId}"
  Version: "1.0.0"
  Classification: "${category || 'General Purpose'}"
  Runtime_Environment: "Python 3.11 / Node.js 20 compatible"
  Target_Execution_Tiers: "Multi-Agent Networks, Sequential Workflows, Direct API Call"

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "${name.replace(/[^a-zA-Z0-9]/g, '')}Inputs",
  "type": "object",
  "properties": {
    "input_data": {
      "type": "string",
      "description": "Primary input for skill execution."
    },
    "parameters": {
      "type": "object",
      "description": "Optional configuration parameters."
    }
  },
  "required": ["input_data"]
}

{
  "title": "${name.replace(/[^a-zA-Z0-9]/g, '')}Outputs",
  "type": "object",
  "properties": {
    "result": {
      "type": "string",
      "description": "Primary output from skill execution."
    },
    "metadata": {
      "type": "object",
      "description": "Execution metadata and diagnostics."
    }
  }
}

PRIMARY_FUNCTION:
${primaryFunction || 'No function defined.'}

INPUT_REQUIREMENTS:
${inputs || 'No input requirements defined.'}

OUTPUT_SPECIFICATIONS:
${outputs || 'No output specifications defined.'}

BEST_PRACTICES:
${bestPractices || 'No best practices defined.'}

COMMON_USE_CASES:
${useCases || 'No use cases defined.'}
`;
}

function generateAgentIdentity(worksheet: Worksheet): string {
	const agentId = slugify(worksheet.title);
	const name = getFieldValue(worksheet, 'name');
	const role = getFieldValue(worksheet, 'role') || getFieldValue(worksheet, 'primary role') || getFieldValue(worksheet, 'system prompt');
	const responsibilities = getFieldValue(worksheet, 'responsibilities') || getFieldValue(worksheet, 'mandates') || getFieldValue(worksheet, 'core mandates');
	const tools = getFieldValue(worksheet, 'tools') || getFieldValue(worksheet, 'available tools');
	const orchestration = getFieldValue(worksheet, 'orchestration') || getFieldValue(worksheet, 'skill orchestration');
	const interactions = getFieldValue(worksheet, 'interactions') || getFieldValue(worksheet, 'interaction');
	const metrics = getFieldValue(worksheet, 'metrics') || getFieldValue(worksheet, 'success');

	// Check for comprehensive agent spec format
	const hasSystemPrompt = worksheet.fields.some(f =>
		f.question.toLowerCase().includes('primary role') ||
		f.question.toLowerCase().includes('system prompt')
	);

	if (hasSystemPrompt) {
		// Comprehensive agent specification
		const example1Input = getFieldValue(worksheet, 'example 1') && worksheet.fields.find(f => f.question.toLowerCase().includes('example 1') && f.question.toLowerCase().includes('user input'));
		const example1Value = example1Input ? (worksheet.responses[example1Input.id] || '') : '';
		const requiredOutputs = getFieldValue(worksheet, 'required outputs');

		// Parse tools into capability mapping format
		const toolLines = tools.split('\n').filter(t => t.trim());
		const capabilityMapping = toolLines.map((line, i) => {
			const toolName = line.replace(/^[-•*]\s*/, '').split('(')[0].trim();
			return `  - tool: "${toolName} (v1.0)"\n    purpose: "Tool capability description."`;
		}).join('\n');

		return `AGENT_IDENTITY:
  Identifier: "${agentId}"
  Version: "1.0.0"
  Target_Role: "${name || 'AI Assistant'}"
  Voice_Tone_Profile: "Professional, creative, highly organized, authoritative"
  Target_Industry: "General Purpose"

ROUTING_DEPENDENCIES:
  Primary_Downstream_Skill: "${slugify(name)}_skill"
  System_Data_Bridge: "${slugify(name)}_data_bridge_mcp"


SYSTEM_PROMPT:
${role || 'You are an AI agent designed to assist with tasks efficiently and effectively.'}

OPERATIONAL MANDATES & EXECUTION STEP SEQUENCE:

${responsibilities || '1. Analyze user requests carefully.\n2. Execute tasks with precision.\n3. Provide clear, actionable responses.'}

${interactions ? `
INTERACTION PATTERNS:
${interactions}` : ''}

CAPABILITY_MAPPING:
${capabilityMapping || '  - tool: "general_capability_tool"\n    purpose: "Standard agent capability."'}

${example1Value ? `
{
  "agent_state": "Processing Request",
  "internal_decisions": [
    "1. Analyzing user input parameters.",
    "2. Selecting appropriate tool for execution.",
    "3. Processing and validating output."
  ],
  "downstream_invocation": {
    "target_skill": "${slugify(name)}_skill",
    "payload": {
      "input_data": "${example1Value.substring(0, 100)}..."
    }
  }
}` : ''}

${requiredOutputs ? `
OUTPUT_REQUIREMENTS:
${requiredOutputs}` : ''}

${metrics ? `
SUCCESS_METRICS:
${metrics}` : ''}
`;
	}

	// Standard agent format
	return `AGENT_IDENTITY:
  Identifier: "${agentId}"
  Version: "1.0.0"
  Target_Role: "${name || 'AI Assistant'}"
  Voice_Tone_Profile: "Professional, helpful, clear"
  Target_Industry: "General Purpose"

SYSTEM_PROMPT:
${role || 'You are an AI agent designed to assist with tasks efficiently and effectively.'}

CORE RESPONSIBILITIES:
${responsibilities || 'No responsibilities defined.'}

AVAILABLE_TOOLS:
${tools || 'No tools specified.'}

SKILL_ORCHESTRATION:
${orchestration || 'No orchestration rules defined.'}

SUCCESS_METRICS:
${metrics || 'No metrics defined.'}
`;
}

function generateWorkflowRegistry(worksheet: Worksheet): string {
	const workflowId = slugify(worksheet.title);
	const name = getFieldValue(worksheet, 'name');
	const triggers = getFieldValue(worksheet, 'triggers');
	const steps = getFieldValue(worksheet, 'steps') || getFieldValue(worksheet, 'sequential steps');
	const decisions = getFieldValue(worksheet, 'decision');
	const errors = getFieldValue(worksheet, 'error');
	const outcomes = getFieldValue(worksheet, 'outcomes');
	const dependencies = getFieldValue(worksheet, 'dependencies');

	// Parse steps into numbered format
	const stepLines = steps.split('\n').filter(s => s.trim());
	const parsedSteps = stepLines.map((line, i) => {
		const stepNum = String(i + 1).padStart(2, '0');
		const stepContent = line.replace(/^[-•*\d.]+\s*/, '').trim();
		return `  STEP_${stepNum}: ${stepContent.toUpperCase().substring(0, 40)}\n    Execute: Detailed execution instructions for this step.\n    Output: \`step_${stepNum}_output\``;
	}).join('\n\n');

	// Parse triggers
	const triggerLines = triggers.split('\n').filter(t => t.trim());
	const parsedTriggers = triggerLines.map((line, i) => {
		const triggerContent = line.replace(/^[-•*\d.]+\s*/, '').trim();
		return `  - trigger_type: "${triggerContent.includes(':') ? triggerContent.split(':')[0].trim() : 'CUSTOM_TRIGGER'}"\n    source: "configured_source"\n    payload_mapping: "input_data -> workflow_payload"`;
	}).join('\n');

	// Parse error handling
	const errorLines = errors.split('\n').filter(e => e.trim());
	const parsedErrors = errorLines.map((line, i) => {
		const errorContent = line.replace(/^[-•*\d.]+\s*/, '').trim();
		return `  - exception: "EXECUTION_TIMEOUT_${i + 1}"\n    strategy: "Retry pipeline segment"\n    max_attempts: 3\n    backoff_coefficient: 2.0\n    fallback: "Log fatal error state; alert operator"`;
	}).join('\n');

	return `WORKFLOW_REGISTRY:
  ID: "${workflowId}"
  Version: "1.0.0"
  Execution_Type: "Event-Driven Sequential Pipeline"
  Concurrency_Limit: 5
  Timeout_Threshold: "600s"

TRIGGER_DEFINITIONS:
${parsedTriggers || '  - trigger_type: "MANUAL_INPUT"\n    source: "chat_interface_channel"\n    payload_mapping: "user_text -> raw_input"'}

SEQUENCE_PIPELINE:

${parsedSteps || '  STEP_01: INITIALIZE\n    Execute: Initialize workflow execution context.\n    Output: \`workflow_context\`\n\n  STEP_02: PROCESS\n    Execute: Execute core workflow logic.\n    Output: \`processed_result\`\n\n  STEP_03: FINALIZE\n    Execute: Complete workflow and generate outputs.\n    Output: \`final_output\`'}

${decisions ? `
ROUTING_LOGIC:
{
  "decision_points": {
    ${decisions.split('\n').map((d, i) => `"condition_${i + 1}": "${d.trim()}"`).join(',\n    ')}
  }
}` : ''}

${errors ? `
EXCEPTION_HANDLING:
${parsedErrors}` : 'EXCEPTION_HANDLING:\n  - exception: "GENERIC_EXECUTION_FAILURE"\n    strategy: "Retry with backoff"\n    max_attempts: 3\n    fallback: "Alert operator, log error"'}

${outcomes ? `
EXPECTED_OUTCOMES:
${outcomes}` : ''}

${dependencies ? `
DEPENDENCIES:
${dependencies}` : ''}

{
  "workflow_state": "READY",
  "active_step": "AWAITING_TRIGGER",
  "execution_context": {
    "workflow_id": "${workflowId}",
    "version": "1.0.0"
  }
}
`;
}

function generateMCPServerRegistry(worksheet: Worksheet): string {
	const mcpName = slugify(worksheet.title);
	const name = getFieldValue(worksheet, 'name');
	const purpose = getFieldValue(worksheet, 'purpose');
	const connection = getFieldValue(worksheet, 'connection');
	const formats = getFieldValue(worksheet, 'formats') || getFieldValue(worksheet, 'data formats');
	const auth = getFieldValue(worksheet, 'auth');
	const usage = getFieldValue(worksheet, 'usage') || getFieldValue(worksheet, 'usage patterns');
	const limits = getFieldValue(worksheet, 'limits') || getFieldValue(worksheet, 'rate limits');

	// Check for comprehensive MCP spec
	const hasTools = worksheet.fields.some(f => f.question.toLowerCase().includes('tools') || f.question.toLowerCase().includes('exposed'));

	let toolsSection = '';
	if (hasTools) {
		toolsSection = `
MCP_EXPOSED_TOOLS:
  - name: "read_resource"
    description: "Reads data from configured data source endpoints."
    inputSchema: {
      "type": "object",
      "properties": {
        "resource_path": { "type": "string" }
      },
      "required": ["resource_path"]
    }

  - name: "write_resource"
    description: "Writes data to configured storage destinations."
    inputSchema: {
      "type": "object",
      "properties": {
        "destination_path": { "type": "string" },
        "content": { "type": "string" }
      },
      "required": ["destination_path", "content"]
    }

  - name: "list_operations"
    description: "Lists available operations and their schemas."
    inputSchema: {
      "type": "object",
      "properties": {}
    }`;
	}

	return `SERVER_REGISTRY:
  Name: "${mcpName}"
  Version: "1.0.0"
  Protocol_Standard: "Model Context Protocol (MCP) v1.0"
  Transport_Layer: "Standard Input/Output (stdio)"
  Runtime_Environment: "Node.js 20+ / TypeScript SDK"
  Execution_Context: "Standard runtime environment"

SECURITY_POLICY:
  Host_Access_Control: "Bound to active user session permissions"
  File_System_Sandbox:
    Enforced_Root_Path: "/workspace/"
    Allowed_Write_Extensions: [".json", ".md", ".txt", ".csv", ".log"]
    Max_Payload_Buffer_Chunk: "10MB"

${purpose ? `PURPOSE:
${purpose}` : ''}

${connection ? `
CONNECTION_CONFIGURATION:
${connection}` : ''}

${formats ? `
DATA_FORMAT_SPECIFICATIONS:
${formats}` : ''}

${auth ? `
AUTHENTICATION_REQUIREMENTS:
${auth}` : ''}

${toolsSection}
${usage ? `
IMPLEMENTATION_PATTERNS:
  - PRE-FLIGHT VALIDATION PATTERN:
    Downstream callers must always validate input schemas before executing tool calls.

  - ANTI-PATTERNS (PROHIBITED EXECUTION):
    Enforce strict blocks against executing unindexed full-drive operations.

  - CACHE ARCHITECTURE:
    Utilize standard local memory caching for schema metadata to minimize overhead.

USAGE_GUIDELINES:
${usage}` : ''}

${limits ? `
RATE_LIMITS_AND_QUOTAS:
${limits}` : ''}

{
  "jsonrpc": "2.0",
  "method": "tools/list",
  "params": {},
  "id": 1
}
`;
}

export function downloadFile(content: string | Blob, filename: string) {
	const blob = content instanceof Blob ? content : new Blob([content], { type: 'text/plain' });
	const url = URL.createObjectURL(blob);
	const link = document.createElement('a');
	link.href = url;
	link.download = filename;
	document.body.appendChild(link);
	link.click();
	document.body.removeChild(link);
	URL.revokeObjectURL(url);
}

export async function exportWorksheet(
	worksheet: Worksheet,
	format: ExportFormat
): Promise<void> {
	const safeName = worksheet.title
		.replace(/[^a-z0-9]/gi, '-')
		.toLowerCase()
		.substring(0, 50);

	// Determine file extension based on worksheet type
	const getExtension = (): string => {
		switch (worksheet.type) {
			case 'skill':
				return 'skill-registry.md';
			case 'agent':
				return 'agent-identity.md';
			case 'workflow':
				return 'workflow-registry.md';
			case 'mcp':
				return 'mcp-server-registry.md';
			default:
				return 'md';
		}
	};

	switch (format) {
		case 'markdown':
			downloadFile(generateMarkdown(worksheet), `${safeName}.md`);
			break;
		case 'html':
			downloadFile(generateHTML(worksheet), `${safeName}.html`);
			break;
		case 'json':
			downloadFile(generateJSON(worksheet), `${safeName}.json`);
			break;
		case 'pdf':
			const pdfBlob = await generatePDF(worksheet);
			downloadFile(pdfBlob, `${safeName}.pdf`);
			break;
		case 'product':
			// Download the final production-ready registry document
			const productContent = generateAssetDocument(worksheet);
			downloadFile(productContent, `${safeName}.${getExtension()}`);
			break;
	}
}